/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.jimsmineshaft.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import net.mcreator.jimsmineshaft.block.WoodenWallTypeBBlock;
import net.mcreator.jimsmineshaft.block.WoodenSupportTypeBBlock;
import net.mcreator.jimsmineshaft.block.WoodenSupportTypeABlock;
import net.mcreator.jimsmineshaft.block.WoodenSupportTopTypeABlock;
import net.mcreator.jimsmineshaft.block.WoodenSupportTopLightTypeABlock;
import net.mcreator.jimsmineshaft.block.WoodenSupportPlainTypeBBlock;
import net.mcreator.jimsmineshaft.block.WoodenSupportFullTypeCBlock;
import net.mcreator.jimsmineshaft.block.WoodenSupportCornerTypeBBlock;
import net.mcreator.jimsmineshaft.block.WoodenSupportCornerTypeB2Block;
import net.mcreator.jimsmineshaft.block.WoodenShelfBlock;
import net.mcreator.jimsmineshaft.block.WoodenShaftLiningBlock;
import net.mcreator.jimsmineshaft.block.WoodenRoofTypeCBlock;
import net.mcreator.jimsmineshaft.block.WoodenRoofTypeBBlock;
import net.mcreator.jimsmineshaft.block.WoodenRoofTypeABlock;
import net.mcreator.jimsmineshaft.block.WoodPileBlock;
import net.mcreator.jimsmineshaft.block.WallSupportedWoodenShelfBlock;
import net.mcreator.jimsmineshaft.block.TiltedCorruptedSupportBeamBlock;
import net.mcreator.jimsmineshaft.block.StrippedRottenSupportBeamBlock;
import net.mcreator.jimsmineshaft.block.SteelShelfBlock;
import net.mcreator.jimsmineshaft.block.StackableSteelShelfBlock;
import net.mcreator.jimsmineshaft.block.RustedMinecartBlock;
import net.mcreator.jimsmineshaft.block.RustedIronSupportCoolBlock;
import net.mcreator.jimsmineshaft.block.RustedIronSupportBlock;
import net.mcreator.jimsmineshaft.block.RustedIronStairsBlock;
import net.mcreator.jimsmineshaft.block.RustedIronRailingCornerBlock;
import net.mcreator.jimsmineshaft.block.RustedIronRailingBlock;
import net.mcreator.jimsmineshaft.block.RustedIronCrossSupportBlock;
import net.mcreator.jimsmineshaft.block.RustedIronCatwalkWallSupportBlock;
import net.mcreator.jimsmineshaft.block.RustedIronCatwalkSupportedBlock;
import net.mcreator.jimsmineshaft.block.RustedIronCatwalkBlock;
import net.mcreator.jimsmineshaft.block.RottenSupportBeamBlock;
import net.mcreator.jimsmineshaft.block.RottenPlanksBlock;
import net.mcreator.jimsmineshaft.block.RottenPlankStairsBlock;
import net.mcreator.jimsmineshaft.block.RottenPlankSlabBlock;
import net.mcreator.jimsmineshaft.block.RottenCabinetBlock;
import net.mcreator.jimsmineshaft.block.RawCopperDrilledNorthDynamiteBlock;
import net.mcreator.jimsmineshaft.block.RawCopperDrilledNorthBlock;
import net.mcreator.jimsmineshaft.block.RawCopperDrilledEastDynamiteBlock;
import net.mcreator.jimsmineshaft.block.RawCopperDrilledEastBlock;
import net.mcreator.jimsmineshaft.block.RawCopper2Block;
import net.mcreator.jimsmineshaft.block.RawCopper29Block;
import net.mcreator.jimsmineshaft.block.RawCopper28Block;
import net.mcreator.jimsmineshaft.block.RawCopper27Block;
import net.mcreator.jimsmineshaft.block.RawCopper26Block;
import net.mcreator.jimsmineshaft.block.RawCopper25Block;
import net.mcreator.jimsmineshaft.block.RawCopper24Block;
import net.mcreator.jimsmineshaft.block.RawCopper23Block;
import net.mcreator.jimsmineshaft.block.RawCopper22Block;
import net.mcreator.jimsmineshaft.block.RawCopper210Block;
import net.mcreator.jimsmineshaft.block.PressureDrillHoldableBlock;
import net.mcreator.jimsmineshaft.block.PressureDrillFoldedModelBlock;
import net.mcreator.jimsmineshaft.block.OldCabinetBlock;
import net.mcreator.jimsmineshaft.block.NewSuspiciousGravelBlock;
import net.mcreator.jimsmineshaft.block.NewStrippedDarkOakLogBlock;
import net.mcreator.jimsmineshaft.block.NewStoneBlock;
import net.mcreator.jimsmineshaft.block.NewGravelBlock;
import net.mcreator.jimsmineshaft.block.MysteryRailBlock;
import net.mcreator.jimsmineshaft.block.MysteryOreBlock;
import net.mcreator.jimsmineshaft.block.MysteryItemBlock;
import net.mcreator.jimsmineshaft.block.LongWoodenShelfBlock;
import net.mcreator.jimsmineshaft.block.LightblockBlock;
import net.mcreator.jimsmineshaft.block.Level1DimensionPortalBlock;
import net.mcreator.jimsmineshaft.block.JimsminedimensionPortalBlock;
import net.mcreator.jimsmineshaft.block.IronSupportBlock;
import net.mcreator.jimsmineshaft.block.IronSidingCornerBlock;
import net.mcreator.jimsmineshaft.block.IronSidingBlock;
import net.mcreator.jimsmineshaft.block.Flashlightb1Block;
import net.mcreator.jimsmineshaft.block.FencedCorruptedSupportBeamBlock;
import net.mcreator.jimsmineshaft.block.ElevatorlightmidblockBlock;
import net.mcreator.jimsmineshaft.block.ElevatorlightBlock;
import net.mcreator.jimsmineshaft.block.ElevatorWheelBlock;
import net.mcreator.jimsmineshaft.block.ElevatorPipesBlock;
import net.mcreator.jimsmineshaft.block.ElevatorLiningCornerRightBlock;
import net.mcreator.jimsmineshaft.block.ElevatorLiningCornerMiddleBlock;
import net.mcreator.jimsmineshaft.block.ElevatorLiningCornerLeftBlock;
import net.mcreator.jimsmineshaft.block.ElevatorLiningBlock;
import net.mcreator.jimsmineshaft.block.ElevatorFrontBlock;
import net.mcreator.jimsmineshaft.block.ElevatorCrossbarSupportBlock;
import net.mcreator.jimsmineshaft.block.ElevatorBraceBlock;
import net.mcreator.jimsmineshaft.block.CorruptedSupportBeamBlock;
import net.mcreator.jimsmineshaft.block.CorruptedSupportBarBlock;
import net.mcreator.jimsmineshaft.block.CopperShardTripleBlock;
import net.mcreator.jimsmineshaft.block.CopperShardDoubleBlock;
import net.mcreator.jimsmineshaft.block.CopperShardBlock;
import net.mcreator.jimsmineshaft.block.CopperFragment5Block;
import net.mcreator.jimsmineshaft.block.CopperFragment4Block;
import net.mcreator.jimsmineshaft.block.CopperFragment3Block;
import net.mcreator.jimsmineshaft.block.CopperFragment2Block;
import net.mcreator.jimsmineshaft.block.CopperFragment1Block;
import net.mcreator.jimsmineshaft.block.CopperChunkTypeEBlock;
import net.mcreator.jimsmineshaft.block.CopperChunkTypeDBlock;
import net.mcreator.jimsmineshaft.block.CopperChunkTypeCBlock;
import net.mcreator.jimsmineshaft.block.CopperChunkTypeBBlock;
import net.mcreator.jimsmineshaft.block.CopperChunkTypeABlock;
import net.mcreator.jimsmineshaft.block.CartRailBroke6Block;
import net.mcreator.jimsmineshaft.block.CartRailBroke5Block;
import net.mcreator.jimsmineshaft.block.CartRailBroke4Block;
import net.mcreator.jimsmineshaft.block.CartRailBroke3Block;
import net.mcreator.jimsmineshaft.block.CartRailBroke2Block;
import net.mcreator.jimsmineshaft.block.CartRailBroke1Block;
import net.mcreator.jimsmineshaft.block.CartRailBlock;
import net.mcreator.jimsmineshaft.block.CanteenBlock;
import net.mcreator.jimsmineshaft.block.CandleHolderBlock;
import net.mcreator.jimsmineshaft.block.CanaryCageBlock;
import net.mcreator.jimsmineshaft.JimsmineshaftMod;

import java.util.function.Function;

public class JimsmineshaftModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(JimsmineshaftMod.MODID);
	public static final DeferredBlock<Block> IRON_SIDING_CORNER = register("iron_siding_corner", IronSidingCornerBlock::new);
	public static final DeferredBlock<Block> ROTTEN_PLANKS = register("rotten_planks", RottenPlanksBlock::new);
	public static final DeferredBlock<Block> ROTTEN_SUPPORT_BEAM = register("rotten_support_beam", RottenSupportBeamBlock::new);
	public static final DeferredBlock<Block> IRON_SIDING = register("iron_siding", IronSidingBlock::new);
	public static final DeferredBlock<Block> WOODEN_SUPPORT_CORNER_TYPE_B = register("wooden_support_corner_type_b", WoodenSupportCornerTypeBBlock::new);
	public static final DeferredBlock<Block> WOODEN_SUPPORT_FULL_TYPE_C = register("wooden_support_full_type_c", WoodenSupportFullTypeCBlock::new);
	public static final DeferredBlock<Block> WOODEN_SUPPORT_TOP_TYPE_A = register("wooden_support_top_type_a", WoodenSupportTopTypeABlock::new);
	public static final DeferredBlock<Block> WOODEN_SUPPORT_PLAIN_TYPE_B = register("wooden_support_plain_type_b", WoodenSupportPlainTypeBBlock::new);
	public static final DeferredBlock<Block> JIMSMINEDIMENSION_PORTAL = register("jimsminedimension_portal", JimsminedimensionPortalBlock::new);
	public static final DeferredBlock<Block> WOODEN_SUPPORT_CORNER_TYPE_B_2 = register("wooden_support_corner_type_b_2", WoodenSupportCornerTypeB2Block::new);
	public static final DeferredBlock<Block> WOODEN_WALL_TYPE_B = register("wooden_wall_type_b", WoodenWallTypeBBlock::new);
	public static final DeferredBlock<Block> WOODEN_SUPPORT_TYPE_A = register("wooden_support_type_a", WoodenSupportTypeABlock::new);
	public static final DeferredBlock<Block> WOODEN_SUPPORT_TOP_LIGHT_TYPE_A = register("wooden_support_top_light_type_a", WoodenSupportTopLightTypeABlock::new);
	public static final DeferredBlock<Block> WOODEN_SUPPORT_TYPE_B = register("wooden_support_type_b", WoodenSupportTypeBBlock::new);
	public static final DeferredBlock<Block> WOODEN_ROOF_TYPE_A = register("wooden_roof_type_a", WoodenRoofTypeABlock::new);
	public static final DeferredBlock<Block> WOODEN_ROOF_TYPE_C = register("wooden_roof_type_c", WoodenRoofTypeCBlock::new);
	public static final DeferredBlock<Block> WOODEN_ROOF_TYPE_B = register("wooden_roof_type_b", WoodenRoofTypeBBlock::new);
	public static final DeferredBlock<Block> STRIPPED_ROTTEN_SUPPORT_BEAM = register("stripped_rotten_support_beam", StrippedRottenSupportBeamBlock::new);
	public static final DeferredBlock<Block> CORRUPTED_SUPPORT_BEAM = register("corrupted_support_beam", CorruptedSupportBeamBlock::new);
	public static final DeferredBlock<Block> TILTED_CORRUPTED_SUPPORT_BEAM = register("tilted_corrupted_support_beam", TiltedCorruptedSupportBeamBlock::new);
	public static final DeferredBlock<Block> STEEL_SHELF = register("steel_shelf", SteelShelfBlock::new);
	public static final DeferredBlock<Block> OLD_CABINET = register("old_cabinet", OldCabinetBlock::new);
	public static final DeferredBlock<Block> ROTTEN_CABINET = register("rotten_cabinet", RottenCabinetBlock::new);
	public static final DeferredBlock<Block> WOOD_PILE = register("wood_pile", WoodPileBlock::new);
	public static final DeferredBlock<Block> RUSTED_MINECART = register("rusted_minecart", RustedMinecartBlock::new);
	public static final DeferredBlock<Block> STACKABLE_STEEL_SHELF = register("stackable_steel_shelf", StackableSteelShelfBlock::new);
	public static final DeferredBlock<Block> WALL_SUPPORTED_WOODEN_SHELF = register("wall_supported_wooden_shelf", WallSupportedWoodenShelfBlock::new);
	public static final DeferredBlock<Block> WOODEN_SHAFT_LINING = register("wooden_shaft_lining", WoodenShaftLiningBlock::new);
	public static final DeferredBlock<Block> WOODEN_SHELF = register("wooden_shelf", WoodenShelfBlock::new);
	public static final DeferredBlock<Block> LONG_WOODEN_SHELF = register("long_wooden_shelf", LongWoodenShelfBlock::new);
	public static final DeferredBlock<Block> FENCED_CORRUPTED_SUPPORT_BEAM = register("fenced_corrupted_support_beam", FencedCorruptedSupportBeamBlock::new);
	public static final DeferredBlock<Block> CORRUPTED_SUPPORT_BAR = register("corrupted_support_bar", CorruptedSupportBarBlock::new);
	public static final DeferredBlock<Block> ROTTEN_PLANK_SLAB = register("rotten_plank_slab", RottenPlankSlabBlock::new);
	public static final DeferredBlock<Block> ROTTEN_PLANK_STAIRS = register("rotten_plank_stairs", RottenPlankStairsBlock::new);
	public static final DeferredBlock<Block> IRON_SUPPORT = register("iron_support", IronSupportBlock::new);
	public static final DeferredBlock<Block> RUSTED_IRON_SUPPORT = register("rusted_iron_support", RustedIronSupportBlock::new);
	public static final DeferredBlock<Block> CANARY_CAGE = register("canary_cage", CanaryCageBlock::new);
	public static final DeferredBlock<Block> RAW_COPPER_DRILLED_EAST = register("raw_copper_drilled_east", RawCopperDrilledEastBlock::new);
	public static final DeferredBlock<Block> COPPER_CHUNK_TYPE_B = register("copper_chunk_type_b", CopperChunkTypeBBlock::new);
	public static final DeferredBlock<Block> COPPER_CHUNK_TYPE_C = register("copper_chunk_type_c", CopperChunkTypeCBlock::new);
	public static final DeferredBlock<Block> COPPER_CHUNK_TYPE_D = register("copper_chunk_type_d", CopperChunkTypeDBlock::new);
	public static final DeferredBlock<Block> COPPER_CHUNK_TYPE_E = register("copper_chunk_type_e", CopperChunkTypeEBlock::new);
	public static final DeferredBlock<Block> COPPER_CHUNK_TYPE_A = register("copper_chunk_type_a", CopperChunkTypeABlock::new);
	public static final DeferredBlock<Block> RAW_COPPER_DRILLED_EAST_DYNAMITE = register("raw_copper_drilled_east_dynamite", RawCopperDrilledEastDynamiteBlock::new);
	public static final DeferredBlock<Block> RAW_COPPER_2 = register("raw_copper_2", RawCopper2Block::new);
	public static final DeferredBlock<Block> NEW_STRIPPED_DARK_OAK_LOG = register("new_stripped_dark_oak_log", NewStrippedDarkOakLogBlock::new);
	public static final DeferredBlock<Block> COPPER_SHARD = register("copper_shard", CopperShardBlock::new);
	public static final DeferredBlock<Block> COPPER_SHARD_TRIPLE = register("copper_shard_triple", CopperShardTripleBlock::new);
	public static final DeferredBlock<Block> MYSTERY_ITEM = register("mystery_item", MysteryItemBlock::new);
	public static final DeferredBlock<Block> CART_RAIL = register("cart_rail", CartRailBlock::new);
	public static final DeferredBlock<Block> ELEVATOR_FRONT = register("elevator_front", ElevatorFrontBlock::new);
	public static final DeferredBlock<Block> COPPER_FRAGMENT_5 = register("copper_fragment_5", CopperFragment5Block::new);
	public static final DeferredBlock<Block> COPPER_FRAGMENT_1 = register("copper_fragment_1", CopperFragment1Block::new);
	public static final DeferredBlock<Block> COPPER_FRAGMENT_2 = register("copper_fragment_2", CopperFragment2Block::new);
	public static final DeferredBlock<Block> COPPER_FRAGMENT_3 = register("copper_fragment_3", CopperFragment3Block::new);
	public static final DeferredBlock<Block> COPPER_FRAGMENT_4 = register("copper_fragment_4", CopperFragment4Block::new);
	public static final DeferredBlock<Block> MYSTERY_RAIL = register("mystery_rail", MysteryRailBlock::new);
	public static final DeferredBlock<Block> RAW_COPPER_210 = register("raw_copper_210", RawCopper210Block::new);
	public static final DeferredBlock<Block> PRESSURE_DRILL_HOLDABLE = register("pressure_drill_holdable", PressureDrillHoldableBlock::new);
	public static final DeferredBlock<Block> COPPER_SHARD_DOUBLE = register("copper_shard_double", CopperShardDoubleBlock::new);
	public static final DeferredBlock<Block> RAW_COPPER_29 = register("raw_copper_29", RawCopper29Block::new);
	public static final DeferredBlock<Block> RAW_COPPER_28 = register("raw_copper_28", RawCopper28Block::new);
	public static final DeferredBlock<Block> RAW_COPPER_27 = register("raw_copper_27", RawCopper27Block::new);
	public static final DeferredBlock<Block> RAW_COPPER_26 = register("raw_copper_26", RawCopper26Block::new);
	public static final DeferredBlock<Block> RAW_COPPER_25 = register("raw_copper_25", RawCopper25Block::new);
	public static final DeferredBlock<Block> RAW_COPPER_24 = register("raw_copper_24", RawCopper24Block::new);
	public static final DeferredBlock<Block> RAW_COPPER_23 = register("raw_copper_23", RawCopper23Block::new);
	public static final DeferredBlock<Block> RAW_COPPER_22 = register("raw_copper_22", RawCopper22Block::new);
	public static final DeferredBlock<Block> NEW_SUSPICIOUS_GRAVEL = register("new_suspicious_gravel", NewSuspiciousGravelBlock::new);
	public static final DeferredBlock<Block> RAW_COPPER_DRILLED_NORTH_DYNAMITE = register("raw_copper_drilled_north_dynamite", RawCopperDrilledNorthDynamiteBlock::new);
	public static final DeferredBlock<Block> NEW_STONE = register("new_stone", NewStoneBlock::new);
	public static final DeferredBlock<Block> PRESSURE_DRILL_FOLDED_MODEL = register("pressure_drill_folded_model", PressureDrillFoldedModelBlock::new);
	public static final DeferredBlock<Block> RAW_COPPER_DRILLED_NORTH = register("raw_copper_drilled_north", RawCopperDrilledNorthBlock::new);
	public static final DeferredBlock<Block> NEW_GRAVEL = register("new_gravel", NewGravelBlock::new);
	public static final DeferredBlock<Block> CANTEEN = register("canteen", CanteenBlock::new);
	public static final DeferredBlock<Block> CANDLE_HOLDER = register("candle_holder", CandleHolderBlock::new);
	public static final DeferredBlock<Block> LEVEL_1_DIMENSION_PORTAL = register("level_1_dimension_portal", Level1DimensionPortalBlock::new);
	public static final DeferredBlock<Block> RUSTED_IRON_CROSS_SUPPORT = register("rusted_iron_cross_support", RustedIronCrossSupportBlock::new);
	public static final DeferredBlock<Block> RUSTED_IRON_RAILING = register("rusted_iron_railing", RustedIronRailingBlock::new);
	public static final DeferredBlock<Block> RUSTED_IRON_CATWALK_WALL_SUPPORT = register("rusted_iron_catwalk_wall_support", RustedIronCatwalkWallSupportBlock::new);
	public static final DeferredBlock<Block> LIGHTBLOCK = register("lightblock", LightblockBlock::new);
	public static final DeferredBlock<Block> RUSTED_IRON_CATWALK = register("rusted_iron_catwalk", RustedIronCatwalkBlock::new);
	public static final DeferredBlock<Block> RUSTED_IRON_CATWALK_SUPPORTED = register("rusted_iron_catwalk_supported", RustedIronCatwalkSupportedBlock::new);
	public static final DeferredBlock<Block> RUSTED_IRON_STAIRS = register("rusted_iron_stairs", RustedIronStairsBlock::new);
	public static final DeferredBlock<Block> RUSTED_IRON_SUPPORT_COOL = register("rusted_iron_support_cool", RustedIronSupportCoolBlock::new);
	public static final DeferredBlock<Block> RUSTED_IRON_RAILING_CORNER = register("rusted_iron_railing_corner", RustedIronRailingCornerBlock::new);
	public static final DeferredBlock<Block> ELEVATOR_CROSSBAR_SUPPORT = register("elevator_crossbar_support", ElevatorCrossbarSupportBlock::new);
	public static final DeferredBlock<Block> ELEVATOR_BRACE = register("elevator_brace", ElevatorBraceBlock::new);
	public static final DeferredBlock<Block> ELEVATOR_PIPES = register("elevator_pipes", ElevatorPipesBlock::new);
	public static final DeferredBlock<Block> ELEVATORLIGHT = register("elevatorlight", ElevatorlightBlock::new);
	public static final DeferredBlock<Block> ELEVATOR_LINING = register("elevator_lining", ElevatorLiningBlock::new);
	public static final DeferredBlock<Block> ELEVATOR_LINING_CORNER_LEFT = register("elevator_lining_corner_left", ElevatorLiningCornerLeftBlock::new);
	public static final DeferredBlock<Block> ELEVATOR_LINING_CORNER_RIGHT = register("elevator_lining_corner_right", ElevatorLiningCornerRightBlock::new);
	public static final DeferredBlock<Block> ELEVATOR_LINING_CORNER_MIDDLE = register("elevator_lining_corner_middle", ElevatorLiningCornerMiddleBlock::new);
	public static final DeferredBlock<Block> ELEVATORLIGHTMIDBLOCK = register("elevatorlightmidblock", ElevatorlightmidblockBlock::new);
	public static final DeferredBlock<Block> ELEVATOR_WHEEL = register("elevator_wheel", ElevatorWheelBlock::new);
	public static final DeferredBlock<Block> FLASHLIGHTB_1 = register("flashlightb_1", Flashlightb1Block::new);
	public static final DeferredBlock<Block> MYSTERY_ORE = register("mystery_ore", MysteryOreBlock::new);
	public static final DeferredBlock<Block> CART_RAIL_BROKE_1 = register("cart_rail_broke_1", CartRailBroke1Block::new);
	public static final DeferredBlock<Block> CART_RAIL_BROKE_2 = register("cart_rail_broke_2", CartRailBroke2Block::new);
	public static final DeferredBlock<Block> CART_RAIL_BROKE_3 = register("cart_rail_broke_3", CartRailBroke3Block::new);
	public static final DeferredBlock<Block> CART_RAIL_BROKE_4 = register("cart_rail_broke_4", CartRailBroke4Block::new);
	public static final DeferredBlock<Block> CART_RAIL_BROKE_5 = register("cart_rail_broke_5", CartRailBroke5Block::new);
	public static final DeferredBlock<Block> CART_RAIL_BROKE_6 = register("cart_rail_broke_6", CartRailBroke6Block::new);

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier, BlockBehaviour.Properties.of());
	}
}